'use strict';function z(g,a,b,c){g.A.qc(g.ab,a,b,c,void 0)}function E(g,a,b,c){g.A.ca?z(g,a,b,c):g.A.hf()._OnMessageFromDOM({type:"event",component:g.ab,handler:a,dispatchOpts:c||null,data:b,responseId:null})}function J(g,a,b){g.A.C(g.ab,a,b)}function L(g,a){for(const [b,c]of a)J(g,b,c)}function M(g){g.Sb||(g.A.Te(g.de),g.Sb=!0)}window.xb=class{constructor(g,a){this.A=g;this.ab=a;this.Sb=!1;this.de=()=>this.Da()}fd(){}Da(){}};function N(g){-1!==g.Pa&&(self.clearTimeout(g.Pa),g.Pa=-1)}
window.Ke=class{constructor(g,a){this.Mc=g;this.yg=a;this.Pa=-1;this.Tb=-Infinity;this.ee=()=>{this.Pa=-1;this.Tb=Date.now();this.gb=!0;this.Mc();this.gb=!1};this.Nd=this.gb=!1}c(){N(this);this.ee=this.Mc=null}};"use strict";function O(g,a){const b=a.elementId,c=g.ic(b,a);g.Y.set(b,c);a.isVisible||(c.style.display="none");a=g.zc(c);a.addEventListener("focus",()=>{P(g,"elem-focused",b)});a.addEventListener("blur",()=>{P(g,"elem-blurred",b)});g.Nb&&document.body.appendChild(c)}
function Q(g,a,b){J(g,a,c=>{const f=g.Y.get(c.elementId);return b(f,c)})}function P(g,a,b,c){c||(c={});c.elementId=b;z(g,a,c)}function R(g,a,b,c){c||(c={});c.elementId=b;E(g,a,c)}
window.kd=class extends self.xb{constructor(g,a){super(g,a);this.Y=new Map;this.Nb=!0;L(this,[["create",b=>O(this,b)],["destroy",b=>{{b=b.elementId;const c=this.Y.get(b);this.Nb&&c.parentElement.removeChild(c);this.Y.delete(b)}}],["set-visible",b=>{this.Nb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Nb){var c=this.Y.get(b.elementId);c.style.left=b.left+"px";c.style.top=b.top+"px";c.style.width=b.width+"px";c.style.height=b.height+"px";b=b.fontSize;
null!==b&&(c.style.fontSize=b+"em")}}],["update-state",b=>{{const c=this.Y.get(b.elementId);this.Wa(c,b)}}],["focus",b=>{{const c=this.zc(this.Y.get(b.elementId));b.focus?c.focus():c.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);Q(this,"get-element",b=>b)}ic(){throw Error("required override");}Wa(){throw Error("required override");
}zc(g){return g}};"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(m){const d=document.createElement("script");d.async=!1;d.type="module";return m.Jg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;d.textContent=m.Ng+`\n\nself["${l}"]();`;document.head.appendChild(d)}):new Promise((k,l)=>{d.onload=k;d.onerror=l;d.src=m;document.head.appendChild(d)})}let c=!1,f=!1;function n(){if(!c){try{new Worker("blob://",{get type(){f=!0}})}catch(m){}c=!0}return f}const p=
/safari\//i.test(navigator.userAgent)&&!/chrome\/|chromium\/|edg\//i.test(navigator.userAgent);let v=new Audio;const B={"audio/webm; codecs=opus":!!v.canPlayType("audio/webm; codecs=opus")&&!p,"audio/ogg; codecs=opus":!!v.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!v.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!v.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!v.canPlayType("audio/mp4"),"audio/mpeg":!!v.canPlayType("audio/mpeg")};v=null;async function D(m){m=
await w(m);return(new TextDecoder("utf-8")).decode(m)}function w(m){return new Promise((d,k)=>{const l=new FileReader;l.onload=q=>d(q.target.result);l.onerror=q=>k(q);l.readAsArrayBuffer(m)})}const x=[];let C=0;window.RealFile=window.File;const F=[],A=new Map,G=new Map;let I=0;const K=[];self.runOnStartup=function(m){if("function"!==typeof m)throw Error("runOnStartup called without a function");K.push(m)};const e=new Set(["cordova","playable-ad","instant-games"]);let h=!1;window.Ca=class m{constructor(d){this.ca=
d.Pg;this.oa=null;this.F="";this.cc=d.Mg;this.vb={};this.Ia=this.ub=null;this.Qb=[];this.jb=this.K=this.Na=null;this.Ma=-1;this.Dg=()=>this.Hf();this.La=[];this.v=d.fe;this.hb="file"===location.protocol.substr(0,4);!this.ca||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&n()||(this.ca=!1);if("playable-ad"===this.v||"instant-games"===this.v)this.ca=!1;if("cordova"===this.v&&this.ca)if(/android/i.test(navigator.userAgent)){const k=/Chrome\/(\d+)/i.exec(navigator.userAgent);k&&90<=parseInt(k[1],
10)||(this.ca=!1)}else this.ca=!1;this.Vb=this.ha=null;"html5"!==this.v&&"playable-ad"!==this.v||!this.hb||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.C("runtime","cordova-fetch-local-file",k=>this.rf(k));this.C("runtime","create-job-worker",()=>this.sf());"cordova"===this.v?document.addEventListener("deviceready",()=>this.zd(d)):this.zd(d)}c(){this.wc();this.oa&&(this.oa=this.oa.onmessage=
null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}Fe(){return g&&"cordova"===this.v}pc(){const d=navigator.userAgent;return g&&e.has(this.v)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(d)}async zd(d){"macos-wkwebview"===this.v&&this.ag();if("playable-ad"===this.v){this.ha=self.c3_base64files;this.Vb={};await this.Ye();for(let l=0,q=d.Qa.length;l<q;++l){var k=d.Qa[l].toLowerCase();this.Vb.hasOwnProperty(k)?
d.Qa[l]={Jg:!0,Ng:this.Vb[k]}:this.ha.hasOwnProperty(k)&&(d.Qa[l]=URL.createObjectURL(this.ha[k]))}}d.Eg?this.F=d.Eg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));d.Rg&&(this.vb=d.Rg);k=new MessageChannel;this.oa=k.port1;this.oa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Df(l));this.jb=new self.Ge(this);await S(this.jb);"object"===typeof window.StatusBar&&
window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ca?await this.kf(d,k.port2):await this.jf(d,k.port2)}Ac(d){d=this.vb.hasOwnProperty(d)?this.vb[d]:d.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:"playable-ad"===this.v&&this.ha.hasOwnProperty(d.toLowerCase())?this.ha[d.toLowerCase()]:d;d instanceof Blob&&(d=URL.createObjectURL(d));return d}async jc(d,k,l){if(d.startsWith("blob:"))return new Worker(d,
l);if("cordova"===this.v&&this.hb)return d=await this.wb(l.Ig?d:this.cc+d),new Worker(URL.createObjectURL(new Blob([d],{type:"application/javascript"})),l);d=new URL(d,k);if(location.origin!==d.origin){d=await fetch(d);if(!d.ok)throw Error("failed to fetch worker script");d=await d.blob();return new Worker(URL.createObjectURL(d),l)}return new Worker(d,l)}va(){return Math.max(window.innerWidth,1)}ua(){return Math.max(window.innerHeight,1)}xd(d){var k=this.jb;return{baseUrl:this.F,windowInnerWidth:this.va(),
windowInnerHeight:this.ua(),devicePixelRatio:window.devicePixelRatio,isFullscreen:m.Ua(),projectData:d.Wg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.Ug||"",exportType:d.fe,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Vg,jobScheduler:{inputPort:k.Sc,outputPort:k.Zc,maxNumWorkers:k.Ag},supportedAudioFormats:B,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||
this.cc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.cc+"opus.wasm.wasm",isFileProtocol:this.hb,isiOSCordova:this.Fe(),isiOSWebView:this.pc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async kf(d,k){var l=this.Ac(d.Qg);this.ub=await this.jc(l,this.F,{type:"module",name:"Runtime",Ig:!0});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;let q=d.ed||[],
u=d.Qa;q=await Promise.all(q.map(r=>this.Ea(r)));u=await Promise.all(u.map(r=>this.Ea(r)));if("cordova"===this.v)for(let r=0,t=d.fc.length;r<t;++r){const y=d.fc[r],H=y[0];if(H===d.cd||"scriptsInEvents.js"===H||H.endsWith("/scriptsInEvents.js"))y[1]=await this.Ea(H)}this.ub.postMessage(Object.assign(this.xd(d),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:q,engineScripts:u,projectScripts:d.fc,mainProjectScript:d.cd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,l,...T(this.jb)]);this.Qb=F.map(r=>new r(this));this.wd();self.c3_callFunction=(r,t)=>this.Na.lf(r,t);"preview"===this.v&&(self.goToLastErrorScript=()=>this.qc("runtime","go-to-last-error-script"))}async jf(d,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Qb=F.map(r=>new r(this));this.wd();var l=d.Qa.map(r=>"string"===typeof r?(new URL(r,this.F)).toString():r);Array.isArray(d.ed)&&l.unshift(...d.ed);l=await Promise.all(l.map(r=>
this.Ea(r)));await Promise.all(l.map(r=>b(r)));l=self.C3_ProjectScriptsStatus;const q=d.cd,u=d.fc;for(let [r,t]of u)if(t||(t=r),r===q)try{t=await this.Ea(t),await b(t),"preview"!==this.v||l[r]||this.Hd(r,"main script did not run to completion")}catch(y){this.Hd(r,y)}else if("scriptsInEvents.js"===r||r.endsWith("/scriptsInEvents.js"))t=await this.Ea(t),await b(t);"preview"===this.v&&"object"!==typeof self.Sg.Tg?(this.Jb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(d=Object.assign(this.xd(d),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:K}),this.Bd(),this.Ia=self.C3_CreateRuntime(d),await self.C3_InitRuntime(this.Ia,d))}Hd(d,k){this.Jb();console.error(`[Preview] Failed to load project main script (${d}): `,k);alert(`Failed to load project main script (${d}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Bd(){this.Jb()}Jb(){const d=
window.Fg;d&&(d.parentElement.removeChild(d),window.Fg=null)}async sf(){const d=await U(this.jb);return{outputPort:d,transferables:[d]}}hf(){if(this.ca)throw Error("not available in worker mode");return this.Ia}qc(d,k,l,q,u){this.oa.postMessage({type:"event",component:d,handler:k,dispatchOpts:q||null,data:l,responseId:null},u)}pd(d,k,l,q,u){const r=I++,t=new Promise((y,H)=>{G.set(r,{resolve:y,reject:H})});this.oa.postMessage({type:"event",component:d,handler:k,dispatchOpts:q||null,data:l,responseId:r},
u);return t}["_OnMessageFromRuntime"](d){const k=d.type;if("event"===k)return this.xf(d);if("result"===k)this.Kf(d);else if("runtime-ready"===k)this.Lf();else if("alert-error"===k)this.Jb(),alert(d.message);else if("creating-runtime"===k)this.Bd();else throw Error(`unknown message '${k}'`);}xf(d){const k=d.component,l=d.handler,q=d.data,u=d.responseId;if(d=A.get(k))if(d=d.get(l)){var r=null;try{r=d(q)}catch(t){console.error(`Exception in '${k}' handler '${l}':`,t);null!==u&&this.Ib(u,!1,""+t);return}if(null===
u)return r;r&&r.then?r.then(t=>this.Ib(u,!0,t)).catch(t=>{console.error(`Rejection from '${k}' handler '${l}':`,t);this.Ib(u,!1,""+t)}):this.Ib(u,!0,r)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Ib(d,k,l){let q;l&&l.transferables&&(q=l.transferables);this.oa.postMessage({type:"result",responseId:d,isOk:k,result:l},q)}Kf(d){const k=d.responseId,l=d.isOk;d=d.result;const q=G.get(k);l?q.resolve(d):q.reject(d);G.delete(k)}C(d,
k,l){let q=A.get(d);q||(q=new Map,A.set(d,q));if(q.has(k))throw Error(`[DOM] Component '${d}' already has handler '${k}'`);q.set(k,l)}static Ra(d){if(F.includes(d))throw Error("DOM handler already added");F.push(d)}wd(){for(const d of this.Qb)if("runtime"===d.ab){this.Na=d;return}throw Error("cannot find runtime DOM handler");}Df(d){this.qc("debugger","message",d)}Lf(){for(const d of this.Qb)d.fd()}static Ua(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
h)}static Id(d){h=!!d}Te(d){this.La.push(d);this.Kc()}Yf(d){d=this.La.indexOf(d);if(-1===d)throw Error("invalid callback");this.La.splice(d,1);this.La.length||this.wc()}Kc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.Dg))}wc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Hf(){this.Ma=-1;for(const d of this.La)d();this.Kc()}ta(d){this.Na.ta(d)}Ba(d){this.Na.Ba(d)}Jc(){this.Na.Jc()}Db(d){this.Na.Db(d)}Ee(){return!!B["audio/webm; codecs=opus"]}async wg(d){d=await this.pd("runtime",
"opus-decode",{arrayBuffer:d},null,[d]);return new Float32Array(d)}De(d){return/^(?:[a-z\-]+:)?\/\//.test(d)||"data:"===d.substr(0,5)||"blob:"===d.substr(0,5)}od(d){return!this.De(d)}async Ea(d){return"cordova"===this.v&&(d.startsWith("file:")||this.hb&&this.od(d))?(d.startsWith(this.F)&&(d=d.substr(this.F.length)),d=await this.wb(d),URL.createObjectURL(new Blob([d],{type:"application/javascript"}))):d}async rf(d){const k=d.filename;switch(d.as){case "text":return await this.we(k);case "buffer":return await this.wb(k);
default:throw Error("unsupported type");}}jd(d){const k=window.cordova.file.applicationDirectory+"www/"+d.toLowerCase();return new Promise((l,q)=>{window.resolveLocalFileSystemURL(k,u=>{u.file(l,q)},q)})}async we(d){d=await this.jd(d);return await D(d)}xc(){if(x.length&&!(8<=C)){C++;var d=x.shift();this.Ze(d.filename,d.Og,d.Hg)}}wb(d){return new Promise((k,l)=>{x.push({filename:d,Og:q=>{C--;this.xc();k(q)},Hg:q=>{C--;this.xc();l(q)}});this.xc()})}async Ze(d,k,l){try{const q=await this.jd(d),u=await w(q);
k(u)}catch(q){l(q)}}ag(){var d={type:"ready"};if("windows-webview2"===this.v)window.chrome.webview.postMessage(JSON.stringify(d));else if("macos-wkwebview"===this.v)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(d));else throw Error("cannot send wrapper message");}async Ye(){const d=[];for(const [k,l]of Object.entries(this.ha))d.push(this.Xe(k,l));await Promise.all(d)}async Xe(d,k){if("object"===typeof k)this.ha[d]=new Blob([k.str],{type:k.type}),this.Vb[d]=k.str;else{let l=await this.ff(k);
l||(l=this.af(k));this.ha[d]=l}}async ff(d){try{return await (await fetch(d)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}af(d){d=this.Sf(d);return this.We(d.data,d.Kg)}Sf(d){var k=d.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=d.substring(k+1);k=d.substring(5,k).split(";");d=k[0]||
"";const q=k[2];l="base64"===k[1]||"base64"===q?atob(l):decodeURIComponent(l);return{Kg:d,data:l}}We(d,k){var l=d.length;let q=l>>2,u=new Uint8Array(l),r=new Uint32Array(u.buffer,0,q),t,y;for(y=t=0;t<q;++t)r[t]=d.charCodeAt(y++)|d.charCodeAt(y++)<<8|d.charCodeAt(y++)<<16|d.charCodeAt(y++)<<24;for(l&=3;l--;)u[y]=d.charCodeAt(y),++y;return new Blob([u],{type:k})}}}"use strict";
{const g=self.Ca;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),c={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,m)=>{const d=document.createElement("link");d.onload=()=>h(d);d.onerror=k=>m(k);d.rel=
"stylesheet";d.href=e;document.head.appendChild(d)})}function v(e){return new Promise((h,m)=>{const d=new Image;d.onload=()=>h(d);d.onerror=k=>m(k);d.src=e})}async function B(e){e=URL.createObjectURL(e);try{return await v(e)}finally{URL.revokeObjectURL(e)}}function D(e){return new Promise((h,m)=>{let d=new FileReader;d.onload=k=>h(k.target.result);d.onerror=k=>m(k);d.readAsText(e)})}async function w(e,h,m){if(!/firefox/i.test(navigator.userAgent))return await B(e);var d=await D(e);d=(new DOMParser).parseFromString(d,
"image/svg+xml");const k=d.documentElement;if(k.hasAttribute("width")&&k.hasAttribute("height")){const l=k.getAttribute("width"),q=k.getAttribute("height");if(!l.includes("%")&&!q.includes("%"))return await B(e)}k.setAttribute("width",h+"px");k.setAttribute("height",m+"px");d=(new XMLSerializer).serializeToString(d);e=new Blob([d],{type:"image/svg+xml"});return await B(e)}function x(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),F=new Set(["canvas","body","html"]);function A(e){F.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function G(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await B(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,m,d,k){e=await w(e,h,m);const l=document.createElement("canvas");l.width=d;l.height=k;l.getContext("2d").drawImage(e,0,0,h,m);return l};let I=!1;document.addEventListener("pause",()=>I=!0);document.addEventListener("resume",()=>I=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}g.Ra(class extends self.xb{constructor(e){super(e,"runtime");this.Sd=!0;this.Oa=-1;this.ad="any";this.Jd=this.Kd=!1;this.Vc=
this.rb=this.xa=null;e.C("canvas","update-size",d=>this.Pf(d));e.C("runtime","invoke-download",d=>this.Bf(d));e.C("runtime","raster-svg-image",d=>this.If(d));e.C("runtime","get-svg-image-size",d=>this.zf(d));e.C("runtime","set-target-orientation",d=>this.Nf(d));e.C("runtime","register-sw",()=>this.Jf());e.C("runtime","post-to-debugger",d=>this.Dd(d));e.C("runtime","go-to-script",d=>this.Dd(d));e.C("runtime","before-start-ticking",()=>this.qf());e.C("runtime","debug-highlight",d=>this.tf(d));e.C("runtime",
"enable-device-orientation",()=>this.Ve());e.C("runtime","enable-device-motion",()=>this.Ue());e.C("runtime","add-stylesheet",d=>this.nf(d));e.C("runtime","alert",d=>this.pf(d));e.C("runtime","hide-cordova-splash",()=>this.Af());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const k=d.target;h.has(k.tagName.toLowerCase())||x(k)||d.preventDefault()});const m=e.K;window.addEventListener("selectstart",A);window.addEventListener("gesturehold",A);m.addEventListener("selectstart",
A);m.addEventListener("gesturehold",A);window.addEventListener("touchstart",A,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",A,{passive:!1}),m.addEventListener("pointerdown",A)):m.addEventListener("touchstart",A);this.ob=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",G,{passive:!1});window.addEventListener("wheel",G,{passive:!1});window.addEventListener("resize",()=>this.Qf());window.addEventListener("fullscreenchange",
()=>this.Xa());window.addEventListener("webkitfullscreenchange",()=>this.Xa());window.addEventListener("mozfullscreenchange",()=>this.Xa());window.addEventListener("fullscreenerror",d=>this.Fc(d));window.addEventListener("webkitfullscreenerror",d=>this.Fc(d));window.addEventListener("mozfullscreenerror",d=>this.Fc(d));e.pc()&&window.addEventListener("focusout",()=>{{const l=document.activeElement;if(l){var d=l.tagName.toLowerCase();var k=new Set("email number password search tel text url".split(" "));
d="textarea"===d?!0:"input"===d?k.has(l.type.toLowerCase()||"text"):x(l)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this.Rf(d);this.Ja=new Set;this.Wb=new WeakSet;this.na=!1}qf(){"cordova"===this.A.v?(document.addEventListener("pause",()=>this.Ic(!0)),document.addEventListener("resume",()=>this.Ic(!1))):document.addEventListener("visibilitychange",()=>this.Ic(document.hidden));return{isSuspended:!(!document.hidden&&!I)}}fd(){window.addEventListener("focus",()=>
this.Za("window-focus"));window.addEventListener("blur",()=>{this.Za("window-blur",{parentHasFocus:K()});this.ob=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||x(h))&&this.Za("keyboard-blur")});window.addEventListener("keydown",h=>this.Cd("keydown",h));window.addEventListener("keyup",h=>this.Cd("keyup",h));window.addEventListener("dblclick",h=>this.Gc("dblclick",h,c));window.addEventListener("wheel",h=>this.Ff(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.Bc(h);this.Ya("pointerdown",h)}),this.A.ca&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.Ke(()=>this.df(),5),this.rb.Nd=!0,window.addEventListener("pointerrawupdate",h=>this.Gf(h))):window.addEventListener("pointermove",h=>this.Ya("pointermove",h)),window.addEventListener("pointerup",h=>this.Ya("pointerup",h)),window.addEventListener("pointercancel",h=>this.Ya("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.Bc(h);this.Hc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Hc("pointermove",h)),window.addEventListener("mouseup",h=>this.Hc("pointerup",h)),window.addEventListener("touchstart",h=>{this.Bc(h);this.Hb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Hb("pointermove",h)),window.addEventListener("touchend",h=>this.Hb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Hb("pointercancel",h)));const e=()=>this.Jc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Za(e,h){z(this,e,h||null,n)}va(){return this.A.va()}ua(){return this.A.ua()}Qf(){const e=this.va(),h=this.ua();this.Za("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ua()});this.A.pc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Ed(e,h,0))}Zf(e,h,m){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Ed(e,
h,m),48)}Ed(e,h,m){const d=this.va(),k=this.ua();this.Oa=-1;d!=e||k!=h?this.Za("window-resize",{innerWidth:d,innerHeight:k,devicePixelRatio:window.devicePixelRatio,isFullscreen:g.Ua()}):10>m&&this.Zf(d,k,m+1)}Nf(e){this.ad=e.targetOrientation}sg(){const e=this.ad;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Xa(){const e=g.Ua();e&&"any"!==this.ad&&this.sg();z(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.va(),innerHeight:this.ua()})}Fc(e){console.warn("[Construct 3] Fullscreen request failed: ",e);z(this,"fullscreenerror",
{isFullscreen:g.Ua(),innerWidth:this.va(),innerHeight:this.ua()})}Ic(e){e?this.A.wc():this.A.Kc();z(this,"visibilitychange",{hidden:e})}Cd(e,h){"Backspace"===h.key&&A(h);const m=b.get(h.code)||h.code;E(this,e,{code:m,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},c)}Ff(e){z(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},c)}Gc(e,h,m){a(h)||E(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},m)}Hc(e,h){if(!a(h)){var m=this.ob;"pointerdown"===e&&0!==m?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");E(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},c);this.ob=h.buttons;this.Gc(h.type,h,f)}}Ya(e,h){if(this.rb&&"pointermove"!==e){var m=this.rb;m.gb||(N(m),m.Tb=Date.now())}m=0;"mouse"===h.pointerType&&(m=this.ob);E(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:m,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},c);"mouse"===h.pointerType&&(m="mousemove","pointerdown"===e?m="mousedown":"pointerup"===e&&(m="mouseup"),this.Gc(m,h,f),this.ob=h.buttons)}Gf(e){this.Vc=e;e=this.rb;if(-1===e.Pa){var h=Date.now(),m=h-e.Tb,d=e.yg;m>=d&&e.Nd?(e.Tb=h,e.gb=!0,e.Mc(),e.gb=!1):e.Pa=self.setTimeout(e.ee,Math.max(d-m,4))}}df(){this.Ya("pointermove",this.Vc);this.Vc=null}Hb(e,h){for(let m=0,d=h.changedTouches.length;m<d;++m){const k=h.changedTouches[m];E(this,e,{pointerId:k.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:k.clientX,clientY:k.clientY,pageX:k.pageX,pageY:k.pageY,width:2*(k.radiusX||k.webkitRadiusX||0),height:2*(k.radiusY||k.webkitRadiusY||0),pressure:k.force||k.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:k.rotationAngle||0,timeStamp:h.timeStamp},c)}}Bc(e){window!==window.top&&window.focus();this.Ad(e.target)&&document.activeElement&&!this.Ad(document.activeElement)&&document.activeElement.blur()}Ad(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Ve(){this.Kd||(this.Kd=!0,window.addEventListener("deviceorientation",e=>this.vf(e)),window.addEventListener("deviceorientationabsolute",e=>this.wf(e)))}Ue(){this.Jd||(this.Jd=!0,window.addEventListener("devicemotion",e=>this.uf(e)))}vf(e){z(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
c)}wf(e){z(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},c)}uf(e){let h=null;var m=e.acceleration;m&&(h={x:m.x||0,y:m.y||0,z:m.z||0});m=null;var d=e.accelerationIncludingGravity;d&&(m={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const k=e.rotationRate;k&&(d={alpha:k.alpha||0,beta:k.beta||0,gamma:k.gamma||0});z(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:m,rotationRate:d,interval:e.interval,timeStamp:e.timeStamp},
c)}Pf(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Sd&&(h.style.display="",this.Sd=!1)}Bf(e){const h=e.url;e=e.filename;const m=document.createElement("a"),d=document.body;m.textContent=e;m.href=h;m.download=e;d.appendChild(m);m.click();d.removeChild(m)}async If(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async zf(e){return await self.C3_GetSvgImageSize(e.blob)}async nf(e){await p(e.url)}Jc(){var e=[...this.Ja];this.Ja.clear();if(!this.na)for(const h of e)(e=h.play())&&e.catch(()=>{this.Wb.has(h)||this.Ja.add(h)})}ta(e){if("function"!==typeof e.play)throw Error("missing play function");this.Wb.delete(e);let h;try{h=e.play()}catch(m){this.Ja.add(e);return}h&&h.catch(()=>{this.Wb.has(e)||this.Ja.add(e)})}Ba(e){this.Ja.delete(e);
this.Wb.add(e)}Db(e){this.na=!!e}Af(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}tf(e){if(e.show){this.xa||(this.xa=document.createElement("div"),this.xa.id="inspectOutline",document.body.appendChild(this.xa));var h=this.xa;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.xa&&(this.xa.style.display="none")}Jf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Dd(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}lf(e,h){return this.A.pd(this.ab,"js-invoke-function",{name:e,params:h},void 0,void 0)}pf(e){alert(e.message)}Rf(e){"entered-fullscreen"===e?(g.Id(!0),this.Xa()):"exited-fullscreen"===e?(g.Id(!1),this.Xa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function S(g){if(g.xg)throw Error("already initialised");g.xg=!0;var a=g.bc.Ac("dispatchworker.js");g.Oc=await g.bc.jc(a,g.F,{name:"DispatchWorker"});a=new MessageChannel;g.Sc=a.port1;g.Oc.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Zc=await U(g)}function T(g){return[g.Sc,g.Zc]}
async function U(g){const a=g.Td.length;var b=g.bc.Ac("jobworker.js");b=await g.bc.jc(b,g.F,{name:"JobWorker"+a});const c=new MessageChannel,f=new MessageChannel;g.Oc.postMessage({type:"_addJobWorker",port:c.port1},[c.port1]);b.postMessage({type:"init",number:a,"dispatch-port":c.port2,"output-port":f.port2},[c.port2,f.port2]);g.Td.push(b);return f.port1}
self.Ge=class{constructor(g){this.bc=g;this.F=g.F;this.F="preview"===g.v?this.F+"workers/":this.F+g.cc;this.Ag=Math.min(navigator.hardwareConcurrency||2,16);this.Oc=null;this.Td=[];this.Zc=this.Sc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ca({Pg:!0,Qg:"workermain.js",Qa:["scripts/c3runtime.js"],fc:[],cd:"",Mg:"scripts/",ed:[],fe:"html5"}));"use strict";
{function g(a){a.stopPropagation()}self.Ca.Ra(class extends self.kd{constructor(a){super(a,"button")}ic(a,b){const c=document.createElement("input");var f=c;b.isCheckbox?(c.type="checkbox",f=document.createElement("label"),f.appendChild(c),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):c.type="button";f.style.position="absolute";f.addEventListener("touchstart",
g);f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);c.addEventListener("click",()=>R(this,"click",a,{isChecked:c.checked}));b.id&&(c.id=b.id);this.Wa(f,b);return f}yd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}zc(a){return this.yd(a)}Wa(a,b){const c=this.yd(a);c.checked=b.isChecked;c.disabled=!b.isEnabled;a.title=b.title;a===c?c.value=b.text:
a.lastChild.textContent=b.text}})}"use strict";async function V(g,a){a=a.type;let b=!0;0===a?b=await W():1===a&&(b=await X());z(g,"permission-result",{type:a,result:b})}async function W(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function X(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Ca.Ra(class extends self.xb{constructor(g){super(g,"touch");J(this,"request-permission",a=>V(this,a))}});"use strict";
{function g(b){b.stopPropagation()}function a(b){13!==b.which&&27!==b.which&&b.stopPropagation()}self.Ca.Ra(class extends self.kd{constructor(b){super(b,"text-input");Q(this,"scroll-to-bottom",c=>this.Mf(c))}ic(b,c){let f;const n=c.type;"textarea"===n?(f=document.createElement("textarea"),f.style.resize="none"):(f=document.createElement("input"),f.type=n);f.style.position="absolute";f.autocomplete="off";f.addEventListener("touchstart",g);f.addEventListener("touchmove",g);f.addEventListener("touchend",
g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",a);f.addEventListener("keyup",a);f.addEventListener("click",p=>{p.stopPropagation();R(this,"click",b)});f.addEventListener("dblclick",p=>{p.stopPropagation();R(this,"dblclick",b)});f.addEventListener("input",()=>P(this,"change",b,{text:f.value}));c.id&&(f.id=c.id);this.Wa(f,c);return f}Wa(b,c){b.value=c.text;b.placeholder=c.placeholder;b.title=c.title;b.disabled=!c.isEnabled;b.readOnly=c.isReadOnly;b.spellcheck=
c.spellCheck;c=c.maxLength;0>c?b.removeAttribute("maxlength"):b.setAttribute("maxlength",c)}Mf(b){b.scrollTop=b.scrollHeight}})}"use strict";
{const g=180/Math.PI;self.da=class extends self.xb{constructor(a){super(a,"audio");this.Pb=this.f=null;this.Rb=this.Rc=!1;this.qa=()=>this.tg();this.aa=[];this.D=[];this.ga=null;this.Ud="";this.Vd=-1;this.qb=new Map;this.Wc=1;this.na=!1;this.bd=0;this.dc=1;this.Pc=0;this.Xd="HRTF";this.Od="inverse";this.Yd=600;this.Wd=1E4;this.$d=1;this.Qd=this.$c=!1;this.ce=this.A.Ee();this.ba=new Map;this.Ga=new Set;this.Tc=!1;this.Xc="";this.ya=null;self.C3Audio_OnMicrophoneStream=(b,c)=>this.Ef(b,c);this.Ob=null;
self.C3Audio_GetOutputStream=()=>this.yf();self.C3Audio_DOMInterface=this;L(this,[["create-audio-context",b=>this.$e(b)],["play",b=>this.Tf(b)],["stop",b=>this.qg(b)],["stop-all",()=>this.rg()],["set-paused",b=>this.jg(b)],["set-volume",b=>this.og(b)],["fade-volume",b=>this.ef(b)],["set-master-volume",b=>this.hg(b)],["set-muted",b=>this.ig(b)],["set-silent",b=>this.lg(b)],["set-looping",b=>this.gg(b)],["set-playback-rate",b=>this.kg(b)],["seek",b=>this.$f(b)],["preload",b=>this.Uf(b)],["unload",b=>
this.ug(b)],["unload-all",()=>this.vg()],["set-suspended",b=>this.mg(b)],["add-effect",b=>this.ud(b)],["set-effect-param",b=>this.dg(b)],["remove-effects",b=>this.Wf(b)],["tick",b=>this.Of(b)],["load-state",b=>this.Cf(b)]])}async $e(a){a.isiOSCordova&&(this.$c=!0);this.bd=a.timeScaleMode;this.Xd=["equalpower","HRTF","soundfield"][a.panningModel];this.Od=["linear","inverse","exponential"][a.distanceModel];this.Yd=a.refDistance;this.Wd=a.maxDistance;this.$d=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.ce||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.vd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.vd()};this.Pb=this.f.createGain();this.Pb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.kc();try{await Promise.all(a.preloadList.map(c=>this.Fb(c.originalUrl,c.url,c.type,!1)))}catch(c){console.error("[Construct 3] Preloading sounds failed: ",c)}return{sampleRate:this.f.sampleRate}}vd(){this.Rb||(this.Rc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Rb=!0)}bf(){this.Rb&&(this.Rc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Rb=!1)}tg(){if(!this.Rc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),c=a.createBufferSource();c.buffer=b;c.connect(a.destination);c.start(0);"running"===a.state&&this.bf()}}W(){return this.f}kc(){return this.f.currentTime}ra(){return this.Pb}md(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.ra()}ge(a,b){a=a.toLowerCase();let c=this.ba.get(a);
c||(c=[],this.ba.set(a,c));b.fg(c.length);b.ng(a);c.push(b);this.Gd(a)}Gd(a){let b=this.ra();const c=this.ba.get(a);if(c&&c.length){b=c[0].P();for(let f=0,n=c.length;f<n;++f){const p=c[f];f+1===n?p.S(this.ra()):p.S(c[f+1].P())}}for(const f of this.la(a))f.Le(b);this.ya&&this.Xc===a&&(this.ya.disconnect(),this.ya.connect(b))}zb(){return this.Wc}Ab(){return this.na}eg(){this.Qd=!0}ye(a,b){return b?this.A.wg(a).then(c=>{const f=this.f.createBuffer(1,c.length,48E3);f.getChannelData(0).set(c);return f}):
new Promise((c,f)=>{this.f.decodeAudioData(a,c,f)})}ta(a){this.A.ta(a)}Ba(a){this.A.Ba(a)}qd(a){let b=0;for(let c=0,f=this.D.length;c<f;++c){const n=this.D[c];this.D[b]=n;n.L===a?n.c():++b}this.D.length=b}Me(){let a=0;for(let b=0,c=this.aa.length;b<c;++b){const f=this.aa[b];this.aa[a]=f;f.sa()?f.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.ze(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Fb(a,b,c,f,n){for(const p of this.aa)if(p.Ta()===b)return await Y(p),
p;if(n)return null;f&&(this.$c||this.Qd)&&this.Me();n="audio/webm; codecs=opus"===c&&!this.ce;f&&n&&this.eg();a=!f||this.$c||n?new self.ue(this,a,b,c,f,n):new self.se(this,a,b,c,f);this.aa.push(a);await Y(a);return a}async yc(a,b,c,f,n){for(const p of this.D)if(p.Ta()===b&&(p.hc()||n))return p.Oe(f),p;a=await this.Fb(a,b,c,n);f="html5"===a.Lc?new self.te(a.i,a,f):new self.ve(a.i,a,f);this.D.push(f);return f}Se(a){let b=this.qb.get(a);if(!b){let c=null;b={dd:0,Lg:new Promise(f=>c=f),resolve:c};this.qb.set(a,
b)}b.dd++}Xf(a){const b=this.qb.get(a);if(!b)throw Error("expected pending tag");b.dd--;0===b.dd&&(b.resolve(),this.qb.delete(a))}vc(a){a||(a=this.Ud);return(a=this.qb.get(a))?a.Lg:Promise.resolve()}Gb(){if(0<this.Ga.size)M(this);else for(const a of this.D)if(a.nd()){M(this);break}}Da(){for(var a of this.Ga)a.Da();a=this.kc();for(var b of this.D)b.Da(a);b=this.D.filter(c=>c.nd()).map(c=>c.Sa());z(this,"state",{tickCount:this.Vd,audioInstances:b,analysers:[...this.Ga].map(c=>c.Be())});0===b.length&&
0===this.Ga.size&&this.Sb&&(this.A.Yf(this.de),this.Sb=!1)}rc(a,b,c){z(this,"trigger",{type:a,tag:b,aiid:c})}async Tf(a){const b=a.originalUrl,c=a.url,f=a.type,n=a.isMusic,p=a.tag,v=a.isLooping,B=a.vol,D=a.pos,w=a.panning;let x=a.off;0<x&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),x=x-a.performanceTime/1E3+a.contextTime):x=x-performance.now()/1E3+this.f.currentTime);this.Ud=p;this.Se(p);try{this.ga=await this.yc(b,c,f,p,n),w?(this.ga.Cb(!0),this.ga.Ne(w.x,w.y,w.angle,
w.innerAngle,w.outerAngle,w.outerGain),w.hasOwnProperty("uid")&&this.ga.Pe(w.uid)):this.ga.Cb(!1),this.ga.Play(v,B,D,x)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Xf(p)}M(this)}qg(a){a=a.tag;for(const b of this.la(a))b.ma()}rg(){for(const a of this.D)a.ma()}jg(a){const b=a.tag;a=a.paused;for(const c of this.la(b))a?c.Va():c.Bb();this.Gb()}og(a){const b=a.tag;a=a.vol;for(const c of this.la(b))c.Eb(a)}async ef(a){const b=a.tag,c=a.vol,f=a.duration;
a=a.stopOnEnd;await this.vc(b);for(const n of this.la(b))n.Ae(c,f,a);this.Gb()}hg(a){this.Wc=a.vol;for(const b of this.D)b.Lb()}ig(a){const b=a.tag;a=a.isMuted;for(const c of this.la(b))c.rd(a)}lg(a){this.na=a.isSilent;this.A.Db(this.na);for(const b of this.D)b.Kb()}gg(a){const b=a.tag;a=a.isLooping;for(const c of this.la(b))c.tc(a)}async kg(a){const b=a.tag;a=a.rate;await this.vc(b);for(const c of this.la(b))c.td(a)}async $f(a){const b=a.tag;a=a.pos;await this.vc(b);for(const c of this.la(b))c.sc(a)}async Uf(a){const b=
a.originalUrl,c=a.url,f=a.type;a=a.isMusic;try{await this.yc(b,c,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async ug(a){if(a=await this.Fb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}vg(){for(const a of this.aa)a.c();this.aa.length=0}mg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.uc(a);a&&this.f.suspend&&this.f.suspend()}Of(a){this.dc=a.timeScale;this.Pc=a.gameTime;this.Vd=a.tickCount;if(0!==
this.bd)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const c of a.instPans){a=c.uid;for(const f of this.D)f.fa===a&&f.sd(c.x,c.y,c.angle)}}async ud(a){var b=a.type;const c=a.tag;var f=a.params;if("filter"===b)f=new self.me(this,...f);else if("delay"===b)f=new self.ke(this,...f);else if("convolution"===b){b=null;try{b=await this.Fb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",
n);return}f=new self.je(this,b.$,...f);f.bg(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)f=new self.ne(this,...f);else if("phaser"===b)f=new self.pe(this,...f);else if("gain"===b)f=new self.oe(this,...f);else if("tremolo"===b)f=new self.re(this,...f);else if("ringmod"===b)f=new self.qe(this,...f);else if("distortion"===b)f=new self.le(this,...f);else if("compressor"===b)f=new self.ie(this,...f);else if("analyser"===b)f=new self.he(this,...f);else throw Error("invalid effect type");this.ge(c,
f);this.Fd()}dg(a){const b=a.index,c=a.param,f=a.value,n=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(c,f,n,p),this.Fd())}Wf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const c of b)c.c();this.ba.delete(a);this.Gd(a)}}Re(a){this.Ga.add(a);this.Gb()}Vf(a){this.Ga.delete(a)}Fd(){this.Tc||(this.Tc=!0,Promise.resolve().then(()=>this.cf()))}cf(){const a={};for(const [b,c]of this.ba)a[b]=c.map(f=>f.Sa());z(this,"fxstate",{fxstate:a});this.Tc=!1}async Cf(a){const b=
a.saveLoadMode;if(3!==b)for(var c of this.D)c.sa()&&1===b||(c.sa()||2!==b)&&c.ma();for(const f of this.ba.values())for(const n of f)n.c();this.ba.clear();this.dc=a.timeScale;this.Pc=a.gameTime;c=a.listenerPos;this.f.listener.setPosition(c[0],c[1],c[2]);this.na=a.isSilent;this.A.Db(this.na);this.Wc=a.masterVolume;c=[];for(const f of Object.values(a.effects))c.push(Promise.all(f.map(n=>this.ud(n))));await Promise.all(c);await Promise.all(a.playing.map(f=>this.mf(f,b)));this.Gb()}async mf(a,b){if(3!==
b){var c=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,p=a.isMusic,v=a.tag,B=a.isLooping,D=a.volume,w=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.yc(c,f,n,v,p)}catch(x){console.error("[Construct 3] Audio: error loading audio state: ",x);return}b.Je(a.pan);b.Play(B,D,w,0);a.isPlaying||b.Va();b.Dc(a)}}}Ef(a,b){this.ya&&this.ya.disconnect();this.Xc=b.toLowerCase();this.ya=this.f.createMediaStreamSource(a);this.ya.connect(this.md(this.Xc))}yf(){this.Ob||(this.Ob=this.f.createMediaStreamDestination(),
this.Pb.connect(this.Ob));return this.Ob.stream}static ze(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Qe(a){return a*g}static xe(a){return Math.pow(10,a/20)}static ld(a){return Math.max(Math.min(self.da.xe(a),1),0)}static Ie(a){return Math.log(a)/Math.log(10)*20}static He(a){return self.da.Ie(Math.max(Math.min(a,1),0))}static Gg(a,b){return 1-Math.exp(-b*a)}};self.Ca.Ra(self.da)}"use strict";function Y(g){g.Ub||(g.Ub=g.Cc());return g.Ub}
self.gd=class{constructor(g,a,b,c,f){this.i=g;this.Cg=a;this.za=b;this.R=c;this.zg=f;this.Lc="";this.Ub=null}c(){this.Ub=this.i=null}Cc(){}W(){return this.i.W()}mc(){return this.Cg}Ta(){return this.za}lc(){return this.R}sa(){return this.zg}ea(){}};"use strict";
self.se=class extends self.gd{constructor(g,a,b,c,f){super(g,a,b,c,f);this.Lc="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.kb=this.lb=null;this.J.addEventListener("canplaythrough",()=>!0);this.pb=this.W().createGain();this.nb=null;this.J.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.J&&(this.nb=this.W().createMediaElementSource(this.J),this.nb.connect(this.pb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.za}' error: `,n);this.kb&&(this.kb(n),this.kb=this.lb=null)})}c(){this.i.qd(this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}Cc(){return new Promise((g,a)=>{this.lb=g;this.kb=a;this.J.src=this.za})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function aa(g){if(g.wa)return g.wa;var a=g.i.A;if("cordova"===a.v&&a.od(g.za)&&a.hb)g.wa=await a.wb(g.za);else{a=await fetch(g.za);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.wa=await a.arrayBuffer()}}async function ba(g){if(g.$)return g.$;g.$=await g.i.ye(g.wa,g.Bg);g.wa=null}
self.ue=class extends self.gd{constructor(g,a,b,c,f,n){super(g,a,b,c,f);this.Lc="webaudio";this.$=this.wa=null;this.Bg=!!n}c(){this.i.qd(this);this.$=this.wa=null;super.c()}async Cc(){try{await aa(this),await ba(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.za}': `,g)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let g=0;self.hd=class{constructor(a,b,c){this.i=a;this.L=b;this.Z=c;this.Mb=g++;this.M=this.W().createGain();this.M.connect(this.ra());this.B=null;this.ib=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.tb=1;this.Ha=!1;this.pa=1;a=this.i.bd;this.Uc=1===a&&!this.sa()||2===a;this.eb=this.fa=-1;this.be=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}ra(){return this.i.md(this.Z)}zb(){return this.i.zb()}yb(){return this.Uc?
this.i.Pc:performance.now()/1E3}mc(){return this.L.mc()}Ta(){return this.L.Ta()}lc(){return this.L.lc()}sa(){return this.L.sa()}Oe(a){this.Z=a}T(){}hc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}nd(){return!this.H&&!this.T()}Aa(){}ea(){return this.L.ea()}Play(){}ma(){}Va(){}Bb(){}Eb(a){this.tb=a;this.M.gain.cancelScheduledValues(0);this.eb=-1;this.M.gain.value=this.nc()}Ae(a,b,c){if(!this.Ha){a*=this.zb();var f=this.M.gain;f.cancelScheduledValues(0);var n=this.i.kc();b=n+b;f.setValueAtTime(f.value,
n);f.linearRampToValueAtTime(a,b);this.tb=a;this.eb=b;this.be=c}}Lb(){this.Eb(this.tb)}Da(a){-1!==this.eb&&a>=this.eb&&(this.eb=-1,this.be&&this.ma(),this.i.rc("fade-ended",this.Z,this.Mb))}nc(){const a=this.tb*this.zb();return isFinite(a)?a:0}rd(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Kb())}Ab(){return this.i.Ab()}Kb(){}tc(){}td(a){this.pa!==a&&(this.pa=a,this.Fa())}Fa(){}sc(){}uc(){}Cb(a){a=!!a;this.ib!==a&&((this.ib=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Xd,this.B.distanceModel=
this.i.Od,this.B.refDistance=this.i.Yd,this.B.maxDistance=this.i.Wd,this.B.rolloffFactor=this.i.$d),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.ra())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.ra())))}Ne(a,b,c,f,n,p){this.ib&&(this.sd(a,b,c),a=self.da.Qe,this.B.coneInnerAngle=a(f),this.B.coneOuterAngle=a(n),this.B.coneOuterGain=p)}sd(a,b,c){this.ib&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(c),this.ia[1]=Math.sin(c),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Pe(a){this.fa=a}oc(){}Le(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Sa(){return{aiid:this.Mb,tag:this.Z,duration:this.ea(),volume:this.tb,isPlaying:this.IsPlaying(),playbackTime:this.Aa(),playbackRate:this.pa,uid:this.fa,bufferOriginalUrl:this.mc(),bufferUrl:"",bufferType:this.lc(),isMusic:this.sa(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.oc(),pan:this.Ce()}}Dc(a){this.td(a.playbackRate);this.rd(a.isMuted)}Ce(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}Je(a){if(a){this.Cb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.Cb(!1)}}}"use strict";
self.te=class extends self.hd{constructor(g,a,b){super(g,a,b);this.L.pb.connect(this.M);this.L.onended=()=>this.Ec()}c(){this.ma();this.L.pb.disconnect();super.c()}O(){return this.L.O()}Ec(){this.H=!0;this.fa=-1;this.i.rc("ended",this.Z,this.Mb)}T(){return this.O().ended}hc(){return this.H?!0:this.T()}Aa(){let g=this.O().currentTime;this.V||(g=Math.min(g,this.ea()));return g}Play(g,a,b){const c=this.O();1!==c.playbackRate&&(c.playbackRate=1);c.loop!==g&&(c.loop=g);this.Eb(a);c.muted&&(c.muted=!1);
if(c.currentTime!==b)try{c.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ta()}' to position '${b}': `,f)}this.i.ta(c);this.G=this.H=!1;this.V=g;this.pa=1}ma(){const g=this.O();g.paused||g.pause();this.i.Ba(g);this.H=!0;this.G=!1;this.fa=-1}Va(){if(!(this.G||this.H||this.T())){var g=this.O();g.paused||g.pause();this.i.Ba(g);this.G=!0}}Bb(){!this.G||this.H||this.T()||(this.i.ta(this.O()),this.G=!1)}Kb(){this.O().muted=this.Ha||this.Ab()}tc(g){g=!!g;this.V!==g&&
(this.V=g,this.O().loop=g)}Fa(){let g=this.pa;this.Uc&&(g*=this.i.dc);try{this.O().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}sc(g){if(!this.H&&!this.T())try{this.O().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}oc(){return this.Aa()}uc(g){g?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.ta(this.O()),this.ka=!1)}};"use strict";
function Z(g){g.j&&g.j.disconnect();g.j=null;g.$a=null}
self.ve=class extends self.hd{constructor(g,a,b){super(g,a,b);this.j=null;this.Xb=c=>this.Ec(c);this.Qc=!0;this.$a=null;this.N=this.Yb=this.Zb=0;this.Yc=1}c(){this.ma();Z(this);this.Xb=null;super.c()}Ec(g){this.G||this.ka||g.target!==this.$a||(this.H=this.Qc=!0,this.fa=-1,Z(this),this.i.rc("ended",this.Z,this.Mb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Qc}hc(){return!this.j||this.H?!0:this.T()}Aa(){let g;g=this.G?this.N:this.Yb+(this.yb()-this.Zb)*this.pa;this.V||(g=Math.min(g,this.ea()));
return g}Play(g,a,b,c){this.Yc=1;this.Eb(a);Z(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.$a=this.j;this.j.onended=this.Xb;this.j.loop=g;this.j.start(c,b);this.G=this.H=this.Qc=!1;this.V=g;this.pa=1;this.Zb=this.yb();this.Yb=b}ma(){if(this.j)try{this.j.stop(0)}catch(g){}this.H=!0;this.G=!1;this.fa=-1}Va(){this.G||this.H||this.T()||(this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}Bb(){!this.G||this.H||this.T()||(Z(this),this.j=
this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.G=!1)}nc(){return super.nc()*this.Yc}Kb(){this.Yc=this.Ha||this.Ab()?0:1;this.Lb()}tc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Fa(){let g=this.pa;this.Uc&&(g*=this.i.dc);this.j&&(this.j.playbackRate.value=g)}sc(g){this.H||this.T()||(this.G?this.N=g:(this.Va(),this.N=g,this.Bb()))}oc(){return this.N}uc(g){g?
this.IsPlaying()?(this.ka=!0,this.N=this.Aa(),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(Z(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.$a=this.j,this.j.onended=this.Xb,this.j.loop=this.V,this.Lb(),this.Fa(),this.j.start(0,this.N),this.Zb=this.yb(),this.Yb=this.N,this.ka=!1)}Dc(g){super.Dc(g);this.N=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Rd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}fg(a){this.Rd=a}ng(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,c,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.f.currentTime;f+=n;switch(c){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Sa(){return{type:this.R,tag:this.Z,params:this.g}}}
self.me=class extends g{constructor(a,b,c,f,n,p,v){super(a);this.R="filter";this.g=[b,c,f,n,p,v];this.l=this.o();this.b=this.o();this.b.gain.value=v;this.a=this.o();this.a.gain.value=1-v;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=c;this.u.detune.value=f;this.u.Q.value=n;this.u.gain.vlaue=p;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,c,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,c,f)}}};self.ke=class extends g{constructor(a,b,c,f){super(a);this.R="delay";this.g=[b,c,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.mb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.cb=this.o();this.cb.gain.value=c;this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b);this.mb.connect(this.U);this.U.connect(this.cb);this.cb.connect(this.mb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.mb.disconnect();this.U.disconnect();this.cb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){const n=self.da.ld;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,c,f);this.m(this.a.gain,1-b,c,f);break;case 4:this.g[1]=n(b);this.m(this.cb.gain,n(b),c,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,c,f)}}};self.je=class extends g{constructor(a,b,c,f){super(a);this.R="convolution";this.g=[c,f];this.Md=this.Ld="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.bb=this.f.createConvolver();this.bb.normalize=c;this.bb.buffer=b;this.l.connect(this.bb);this.l.connect(this.a);this.bb.connect(this.b)}c(){this.l.disconnect();this.bb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}bg(a,b){this.Ld=a;this.Md=b}Sa(){const a=
super.Sa();a.bufferOriginalUrl=this.Ld;a.bufferUrl="";a.bufferType=this.Md;return a}};self.ne=class extends g{constructor(a,b,c,f,n,p){super(a);this.R="flanger";this.g=[b,c,f,n,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.fb=this.o();this.fb.gain.value=n;this.U=this.f.createDelay(b+c);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.I=this.o();this.I.gain.value=c;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.fb);this.fb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.fb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,c,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,c,f);break;case 8:this.g[3]=b/100,this.m(this.fb.gain,b/100,c,f)}}};self.pe=class extends g{constructor(a,b,c,f,n,p,v){super(a);this.R="phaser";this.g=[b,c,f,n,p,v];this.l=this.o();this.a=this.o();this.a.gain.value=1-v/2;this.b=this.o();this.b.gain.value=v/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
c;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.I);this.I.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,c,f);this.m(this.a.gain,1-b/2,c,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,c,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,c,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,c,f);break;case 6:this.g[3]=b;this.m(this.I.gain,b,c,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,c,f)}}};self.oe=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){const n=self.da.ld;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),c,f)}}};self.re=class extends g{constructor(a,b,c){super(a);this.R="tremolo";this.g=[b,c];this.h=this.o();this.h.gain.value=1-c/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=c/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,c,f);this.m(this.I.gain,b/2,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.qe=class extends g{constructor(a,b,c){super(a);this.R="ringmod";this.g=[b,c];this.l=this.o();this.b=this.o();this.b.gain.value=c;this.a=this.o();this.a.gain.value=1-c;this.sb=this.o();this.sb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.sb.gain);this.s.start(0);this.l.connect(this.sb);this.l.connect(this.a);this.sb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.sb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,c,f);
this.m(this.a.gain,1-b,c,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,c,f)}}};self.le=class extends g{constructor(a,b,c,f,n,p){super(a);this.R="distortion";this.g=[b,c,f,n,p];this.l=this.o();this.ac=this.o();this.$b=this.o();this.cg(f,n);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ec=this.f.createWaveShaper();this.Nc=new Float32Array(65536);this.gf(b,c);this.ec.curve=this.Nc;this.l.connect(this.ac);this.l.connect(this.a);this.ac.connect(this.ec);this.ec.connect(this.$b);
this.$b.connect(this.b)}c(){this.l.disconnect();this.ac.disconnect();this.ec.disconnect();this.$b.disconnect();this.b.disconnect();this.a.disconnect();super.c()}cg(a,b){.01>a&&(a=.01);this.ac.gain.value=a;this.$b.gain.value=Math.pow(1/a,.6)*b}gf(a,b){for(let c=0;32768>c;++c){let f=c/32768;f=this.pg(f,a,b);this.Nc[32768+c]=f;this.Nc[32768-c-1]=-f}}pg(a,b,c){c=1.05*c*b-b;const f=0>a?-a:a;return(f<b?f:b+c*self.da.Gg(f-b,1/c))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,c,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,c,f),this.m(this.a.gain,1-b,c,f)}}};self.ie=class extends g{constructor(a,b,c,f,n,p){super(a);this.R="compressor";this.g=[b,c,f,n,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=c;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.he=class extends g{constructor(a,b,c){super(a);this.R="analyser";this.g=[b,c];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=c;this.Pd=new Float32Array(this.h.frequencyBinCount);this.ae=new Uint8Array(b);this.Zd=this.Ka=0;this.i.Re(this)}c(){this.i.Vf(this);this.h.disconnect();super.c()}Da(){this.h.getFloatFrequencyData(this.Pd);this.h.getByteTimeDomainData(this.ae);const a=this.h.fftSize;let b=this.Ka=0;for(var c=0;c<a;++c){let f=(this.ae[c]-128)/128;0>f&&(f=-f);
this.Ka<f&&(this.Ka=f);b+=f*f}c=self.da.He;this.Ka=c(this.Ka);this.Zd=c(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Be(){return{tag:this.Z,index:this.Rd,peak:this.Ka,rms:this.Zd,binCount:this.h.frequencyBinCount,freqBins:this.Pd}}}};
